version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build Docker image
          command: |
            echo "PORT=${PORT}" >> .env
            echo "APP_ENV=${APP_ENV}" >> .env
            docker build -t $DOCKER_USERNAME/$CIRCLE_PROJECT_REPONAME:latest -f .docker/Dockerfile .
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/$CIRCLE_PROJECT_REPONAME:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push:
          context: docker-hub-creds 